# Generated by Django 2.0.6 on 2019-09-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_siteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='roleId',
        ),
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
